mod header_key;
mod header_map;
mod header_value;

pub use header_key::HeaderKey;
pub use header_map::HeaderMap;
pub use header_value::HeaderValue;
use std::collections::HashSet;

lazy_static! {
    static ref COMMON_HEADERS: HashSet<String> = {
        let mut m = HashSet::new();
        m.insert("A-IM".to_string());
        m.insert("Accept".to_string());
        m.insert("Accept-Charset".to_string());
        m.insert("Accept-Datetime".to_string());
        m.insert("Accept-Encoding".to_string());
        m.insert("Accept-Language".to_string());
        m.insert("Access-Control-Request-Method".to_string());
        m.insert("Access-Control-Request-Headers".to_string());
        m.insert("Authorization".to_string());
        m.insert("Cache-Control".to_string());
        m.insert("Connection".to_string());
        m.insert("Content-Encoding".to_string());
        m.insert("Content-Length".to_string());
        m.insert("Content-MD5".to_string());
        m.insert("Content-Type".to_string());
        m.insert("Cookie".to_string());
        m.insert("Date".to_string());
        m.insert("Expect".to_string());
        m.insert("Forwarded".to_string());
        m.insert("From".to_string());
        m.insert("Host".to_string());
        m.insert("HTTP2-Settings".to_string());
        m.insert("If-Match".to_string());
        m.insert("If-Modified-Since".to_string());
        m.insert("If-None-Match".to_string());
        m.insert("If-Range".to_string());
        m.insert("If-Unmodified-Since".to_string());
        m.insert("Max-Forwards".to_string());
        m.insert("Origin".to_string());
        m.insert("Pragma".to_string());
        m.insert("Prefer".to_string());
        m.insert("Proxy-Authorization".to_string());
        m.insert("Range".to_string());
        m.insert("Referer".to_string());
        m.insert("TE".to_string());
        m.insert("Trailer".to_string());
        m.insert("Transfer-Encoding".to_string());
        m.insert("User-Agent".to_string());
        m.insert("Upgrade".to_string());
        m.insert("Via".to_string());
        m.insert("Warning".to_string());
        m.insert("Accept-CH".to_string());
        m.insert("Access-Control-Allow-Origin".to_string());
        m.insert("Access-Control-Allow-Credentials".to_string());
        m.insert("Access-Control-Expose-Headers".to_string());
        m.insert("Access-Control-Max-Age".to_string());
        m.insert("Access-Control-Allow-Methods".to_string());
        m.insert("Access-Control-Allow-Headers".to_string());
        m.insert("Accept-Patch".to_string());
        m.insert("Accept-Ranges".to_string());
        m.insert("Age".to_string());
        m.insert("Allow".to_string());
        m.insert("Alt-Svc".to_string());
        m.insert("Cache-Control".to_string());
        m.insert("Connection".to_string());
        m.insert("Content-Disposition".to_string());
        m.insert("Content-Encoding".to_string());
        m.insert("Content-Language".to_string());
        m.insert("Content-Length".to_string());
        m.insert("Content-Location".to_string());
        m.insert("Content-MD5".to_string());
        m.insert("Content-Range".to_string());
        m.insert("Content-Type".to_string());
        m.insert("Date".to_string());
        m.insert("Delta-Base".to_string());
        m.insert("ETag".to_string());
        m.insert("Expires".to_string());
        m.insert("IM".to_string());
        m.insert("Last-Modified".to_string());
        m.insert("Link".to_string());
        m.insert("Location".to_string());
        m.insert("P3P".to_string());
        m.insert("Pragma".to_string());
        m.insert("Preference-Applied".to_string());
        m.insert("Proxy-Authenticate".to_string());
        m.insert("Public-Key-Pins".to_string());
        m.insert("Retry-After".to_string());
        m.insert("Server".to_string());
        m.insert("Set-Cookie".to_string());
        m.insert("Strict-Transport-Security".to_string());
        m.insert("Trailer".to_string());
        m.insert("Transfer-Encoding".to_string());
        m.insert("Tk".to_string());
        m.insert("Upgrade".to_string());
        m.insert("Vary".to_string());
        m.insert("Via".to_string());
        m.insert("Warning".to_string());
        m.insert("WWW-Authenticate".to_string());
        m
    };
}
